$(document).ready(function(){
    $("#btn1").click(function(){
    $("#my1").modal();
    });
    $("#btn2").click(function(){
    $("#my2").modal();
    });
    $("#btn3").click(function(){
    $("#my3").modal();
    });
    $("#btn4").click(function(){
    $("#my4").modal();
    });
    $("#btn5").click(function(){
    $("#my5").modal();
    });
    $("#btn6").click(function(){
    $("#my6").modal();
    });
    $("#btn7").click(function(){
    $("#my7").modal();
    });
    $("#btn8").click(function(){
    $("#my8").modal();
    });
    $("#btn9").click(function(){
    $("#my9").modal();
    });
    $("#btn10").click(function(){
    $("#my10").modal();
    });
    $("#btn11").click(function(){
    $("#my11").modal();
    });
    $("#btn12").click(function(){
    $("#my12").modal();
    });
    $("#btn13").click(function(){
    $("#my13").modal();
    });
    $("#btn14").click(function(){
    $("#my14").modal();
    });
    $("#btn15").click(function(){
    $("#my15").modal();
    });
    $("#btn16").click(function(){
    $("#my16").modal();
    });
    $("#btn17").click(function(){
    $("#my17").modal();
    });
    $("#btn18").click(function(){
    $("#my18").modal();
    });
    $("#btn19").click(function(){
    $("#my19").modal();
    });
    $("#btn20").click(function(){
    $("#my20").modal();
    });
    $("#btn21").click(function(){
    $("#my21").modal();
    });
    $("#btn22").click(function(){
    $("#my22").modal();
    });
    $("#btn23").click(function(){
    $("#my23").modal();
    });
    $("#btn24").click(function(){
    $("#my24").modal();
    });
    $("#btn25").click(function(){
    $("#my25").modal();
    });
    $("#btn26").click(function(){
    $("#my26").modal();
    });
    $("#btn27").click(function(){
    $("#my27").modal();
    });
    $("#btn28").click(function(){
    $("#my28").modal();
    });
    $("#btn29").click(function(){
    $("#my29").modal();
    });
    $("#btn30").click(function(){
    $("#my30").modal();
    });
    $("#btn31").click(function(){
    $("#my31").modal();
    });
    $("#btn32").click(function(){
    $("#my32").modal();
    });
    $("#btn33").click(function(){
    $("#my33").modal();
    });
    $("#btn34").click(function(){
    $("#my34").modal();
    });
    $("#btn35").click(function(){
    $("#my35").modal();
    });
    $("#btn36").click(function(){
    $("#my36").modal();
    });
    $("#btn37").click(function(){
    $("#my37").modal();
    });
    $("#btn38").click(function(){
    $("#my38").modal();
    });
    $("#btn39").click(function(){
    $("#my39").modal();
    });
    $("#btn40").click(function(){
    $("#my40").modal();
    });
    $("#btn40").click(function(){
    $("#my40").modal();
    });
    $("#btn41").click(function(){
    $("#my41").modal();
    });
    $("#btn42").click(function(){
    $("#my42").modal();
    });
    $("#btn43").click(function(){
    $("#my43").modal();
    });
    $("#btn44").click(function(){
    $("#my44").modal();
    });
    $("#btn45").click(function(){
    $("#my45").modal();
    });
    $("#btn46").click(function(){
    $("#my46").modal();
    });
    $("#btn47").click(function(){
    $("#my47").modal();
    });
    $("#btn48").click(function(){
    $("#my48").modal();
    });
    $("#btn49").click(function(){
    $("#my49").modal();
    });
    $("#btn50").click(function(){
    $("#my50").modal();
    });
    $("#btn51").click(function(){
    $("#my51").modal();
    });
    $("#btn52").click(function(){
    $("#my52").modal();
    });
    $("#btn53").click(function(){
    $("#my53").modal();
    });
    $("#btn54").click(function(){
    $("#my54").modal();
    });
    $("#btn55").click(function(){
    $("#my55").modal();
    });
    $("#btn56").click(function(){
    $("#my56").modal();
    });
    $("#btn57").click(function(){
    $("#my57").modal();
    });
    $("#btn58").click(function(){
    $("#my58").modal();
    });
    $("#btn59").click(function(){
    $("#my59").modal();
    });
    $("#btn60").click(function(){
    $("#my60").modal();
    });
    $("#btn61").click(function(){
    $("#my61").modal();
    });
    $("#btn62").click(function(){
    $("#my62").modal();
    });
    $("#btn63").click(function(){
    $("#my63").modal();
    });
    $("#btn64").click(function(){
    $("#my64").modal();
    });
    $("#btn65").click(function(){
    $("#my65").modal();
    });
    $("#btn66").click(function(){
    $("#my66").modal();
    });
    $("#btn67").click(function(){
    $("#my67").modal();
    });
    $("#btn68").click(function(){
    $("#my68").modal();
    });
    $("#btn69").click(function(){
    $("#my69").modal();
    });
    $("#btn70").click(function(){
    $("#my70").modal();
    });
    $("#btn71").click(function(){
    $("#my71").modal();
    });
    $("#btn72").click(function(){
    $("#my72").modal();
    });
    $("#btn73").click(function(){
    $("#my73").modal();
    });
    $("#btn74").click(function(){
    $("#my74").modal();
    });
    $("#btn75").click(function(){
    $("#my75").modal();
    });
    $("#btn76").click(function(){
    $("#my76").modal();
    });
    $("#btn77").click(function(){
    $("#my77").modal();
    });
    $("#btn78").click(function(){
    $("#my78").modal();
    });
    $("#btn79").click(function(){
    $("#my79").modal();
    });
    $("#btn80").click(function(){
    $("#my80").modal();
    });
    $("#btn81").click(function(){
    $("#my81").modal();
    });
    $("#btn82").click(function(){
    $("#my82").modal();
    });
    $("#btn83").click(function(){
    $("#my83").modal();
    });
    $("#btn84").click(function(){
    $("#my84").modal();
    });
    $("#btn85").click(function(){
    $("#my85").modal();
    });
    $("#btn86").click(function(){
    $("#my86").modal();
    });
    $("#btn87").click(function(){
    $("#my87").modal();
    });
    $("#btn88").click(function(){
    $("#my88").modal();
    });
    $("#btn89").click(function(){
    $("#my89").modal();
    });
    $("#btn90").click(function(){
    $("#my90").modal();
    });
    $("#btn91").click(function(){
    $("#my91").modal();
    });
    $("#btn92").click(function(){
    $("#my92").modal();
    });
    $("#btn93").click(function(){
    $("#my93").modal();
    });
    $("#btn94").click(function(){
    $("#my94").modal();
    });
    $("#btn95").click(function(){
    $("#my95").modal();
    });
    $("#btn96").click(function(){
    $("#my96").modal();
    });
    $("#btn97").click(function(){
    $("#my97").modal();
    });
    $("#btn98").click(function(){
    $("#my98").modal();
    });
    $("#btn99").click(function(){
    $("#my99").modal();
    });
    $("#btn100").click(function(){
    $("#my100").modal();
    });
    $("#btn101").click(function(){
    $("#my101").modal();
    });
    $("#btn102").click(function(){
    $("#my102").modal();
    });
    $("#btn103").click(function(){
    $("#my103").modal();
    });
    $("#btn104").click(function(){
    $("#my104").modal();
    });
    $("#btn105").click(function(){
    $("#my105").modal();
    });
    $("#btn106").click(function(){
    $("#my106").modal();
    });
    $("#btn107").click(function(){
    $("#my107").modal();
    });
    $("#btn108").click(function(){
    $("#my108").modal();
    });
    $("#btn109").click(function(){
    $("#my109").modal();
    });
    $("#btn110").click(function(){
    $("#my110").modal();
    });
    $("#btn111").click(function(){
    $("#my111").modal();
    });
    $("#btn112").click(function(){
    $("#my112").modal();
    });
    $("#btn113").click(function(){
    $("#my113").modal();
    });
    $("#btn114").click(function(){
    $("#my114").modal();
    });
    $("#btn115").click(function(){
    $("#my115").modal();
    });
    $("#btn116").click(function(){
    $("#my116").modal();
    });
    $("#btn117").click(function(){
    $("#my117").modal();
    });
    $("#btn118").click(function(){
    $("#my118").modal();
    });
    $("#btn119").click(function(){
    $("#my119").modal();
    });
    $("#btn120").click(function(){
    $("#my120").modal();
    });
    $("#btn121").click(function(){
    $("#my121").modal();
    });
    $("#btn122").click(function(){
    $("#my122").modal();
    });
    $("#btn123").click(function(){
    $("#my123").modal();
    });
    $("#btn124").click(function(){
    $("#my124").modal();
    });
    $("#btn125").click(function(){
    $("#my125").modal();
    });
    $("#btn126").click(function(){
    $("#my126").modal();
    });
    $("#btn127").click(function(){
    $("#my127").modal();
    });
    $("#btn128").click(function(){
    $("#my128").modal();
    });
    $("#btn129").click(function(){
    $("#my129").modal();
    });
    $("#btn130").click(function(){
    $("#my130").modal();
    });
    $("#btn131").click(function(){
    $("#my131").modal();
    });
    $("#btn132").click(function(){
    $("#my132").modal();
    });
    $("#btn133").click(function(){
    $("#my133").modal();
    });
    $("#btn134").click(function(){
    $("#my134").modal();
    });
    $("#btn135").click(function(){
    $("#my135").modal();
    });
    $("#btn136").click(function(){
    $("#my136").modal();
    });
    $("#btn137").click(function(){
    $("#my137").modal();
    });
    $("#btn138").click(function(){
    $("#my138").modal();
    });
    $("#btn139").click(function(){
    $("#my139").modal();
    });
    $("#btn140").click(function(){
    $("#my140").modal();
    });
    $("#btn141").click(function(){
    $("#my141").modal();
    });
    $("#btn142").click(function(){
    $("#my142").modal();
    });
    $("#btn143").click(function(){
    $("#my143").modal();
    });
    $("#btn144").click(function(){
    $("#my144").modal();
    });
    $("#btn145").click(function(){
    $("#my145").modal();
    });
    $("#btn146").click(function(){
    $("#my146").modal();
    });
    $("#btn147").click(function(){
    $("#my147").modal();
    });
    $("#btn148").click(function(){
    $("#my148").modal();
    });
    $("#btn149").click(function(){
    $("#my149").modal();
    });
    $("#btn150").click(function(){
    $("#my150").modal();
    });
    $("#btn151").click(function(){
    $("#my151").modal();
    });
    $("#btn152").click(function(){
    $("#my152").modal();
    });
    $("#btn153").click(function(){
    $("#my153").modal();
    });
    $("#btn154").click(function(){
    $("#my154").modal();
    });
    $("#btn155").click(function(){
    $("#my155").modal();
    });
    $("#btn156").click(function(){
    $("#my156").modal();
    });
    $("#btn157").click(function(){
    $("#my157").modal();
    });
    $("#btn158").click(function(){
    $("#my158").modal();
    });
    $("#btn159").click(function(){
    $("#my159").modal();
    });
    $("#btn160").click(function(){
    $("#my160").modal();
    });
    $("#btn161").click(function(){
    $("#my161").modal();
    });
    $("#btn162").click(function(){
    $("#my162").modal();
    });
    $("#btn163").click(function(){
    $("#my163").modal();
    });
    $("#btn164").click(function(){
    $("#my164").modal();
    });
    $("#btn165").click(function(){
    $("#my165").modal();
    });
    $("#btn166").click(function(){
    $("#my166").modal();
    });
    $("#btn167").click(function(){
    $("#my167").modal();
    });
    $("#btn168").click(function(){
    $("#my168").modal();
    });
    $("#btn169").click(function(){
    $("#my169").modal();
    });
    $("#btn170").click(function(){
    $("#my170").modal();
    });
    $("#btn171").click(function(){
    $("#my171").modal();
    });
    $("#btn172").click(function(){
    $("#my172").modal();
    });
    $("#btn173").click(function(){
    $("#my173").modal();
    });
    $("#btn174").click(function(){
    $("#my174").modal();
    });
    $("#btn175").click(function(){
    $("#my175").modal();
    });
    $("#btn176").click(function(){
    $("#my176").modal();
    });
    $("#btn177").click(function(){
    $("#my177").modal();
    });
    $("#btn178").click(function(){
    $("#my178").modal();
    });
   
    
    
    











});